version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust
    groups:
      rust-crates:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust
    groups:
      tauri-crates:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm
    groups:
      npm-packages:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
